# wix 프로토타입 개발
## df_merged1 정제 및 병합 과정 요약
- 이미지 분석 결과(`df_이미지분류`)와 감성 예측 결과(`df_감성예측`)를 숙소ID 기준으로 병합함.
- 병합 방식은 inner join으로, 두 데이터 모두에 존재하는 숙소ID만 남김.
- 병합 후, 리뷰내용, 작성일, 별점, 동반유형 등 분석에 불필요한 컬럼은 삭제하여 데이터 정제함.
- 최종적으로 df_merged1에는 숙소ID별 이미지 분류 정보와 감성 예측 정보만 남음.

In [26]:
import pandas as pd
df_공연 = pd.read_csv('공연전시크롤링.csv')
df_레저 = pd.read_csv('레저크롤링.csv')
df_감성예측 = pd.read_csv('야놀자_감성예측완료.csv')
df_메인 = pd.read_csv('../프로젝트/0822_메인프레임v13.csv')
df_이미지분류 = pd.read_csv('vertex_image_analysis_results.csv')

## 이미지 분류 컬럼명 변경 및 숙소 스타일과 감성 예측 병합

In [27]:
# 컬럼명 변경
df_이미지분류 = df_이미지분류.rename(columns={'file_id': '숙소ID'})

In [28]:
df_이미지분류.head()

         숙소ID  color    style   view
0  1000003240  white  minimal  ocean
1     1000052  white  classic  other
2  1000074159  white  minimal  ocean
3  1000080217   dark  minimal  other
4  1000080247  white  minimal  other

In [29]:
df_감성예측.head()

,숙소ID,별점,작성자,동반유형,리뷰내용,작성일,감성별점
0,23184,1,스테판트로*,출장,원래 모텔 믿거하는데 다음 일정 때문에 급해서 예약했습니다. 객실 흡연 가능한 곳입...,2025.06.12,1
1,23184,1,라스트노블**,친구와 함께,일단 친절도 최악임.\n\n주차문제 차량이용 가능하다며\n어떠한 내용 및 고지도 없...,2025.06.05,1
2,23184,1,해망동짝쓰**,연인과 함께,"기차와 지하철이 선로 근처이며 , 입실시간이 생각보다 많이 늦더라구요",2025.04.14,2
3,23184,1,랄라느림보****,연인과 함께,너무 불친절해요 ㅠㅠ 소음고 있구..방은 괜찮은데 화장실은 깨끗한지도 모르겠어요 ㅠ...,2024.09.07,1
4,23184,1,허둥지둥개****,NaN,선착순배정이라 흡연실 배정돼서 담배냄새가 엄청났네요. 이거까진 흡연실이니까 그러려니...,2024.06.10,1

- 리뷰내용,작성일,별점,동반유형 은 삭제

In [30]:
# 숙소ID 기준으로 df_이미지분류 df_감성예측 병합
df_merged1 = pd.merge(df_이미지분류, df_감성예측, on='숙소ID', how='inner')

In [31]:
df_merged1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 643843 entries, 0 to 643842
Data columns (total 10 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   숙소ID    643843 non-null  int64
 1   color   643843 non-null  object
 2   style   643843 non-null  object
 3   view    643843 non-null  object
 4   별점      643843 non-null  int64
 5   작성자     643843 non-null  object
 6   동반유형    214177 non-null  object
 7   리뷰내용    643618 non-null  object
 8   작성일     643843 non-null  object
 9   감성별점    643843 non-null  int64
dtypes: int64(3), object(7)
memory usage: 49.1+ MB

In [32]:
df_merged1.head()

,숙소ID,color,style,view,별점,작성자,동반유형,리뷰내용,작성일,감성별점
0,1000003240,white,minimal,ocean,1,니제*,NaN,"바다 안보임, 테라스 금연, 식수 없음, 객실 청결상태 안좋음, 드라이도 사용하기 ...",2022.10.02,1
1,1000003240,white,minimal,ocean,2,브뤼셀*****,NaN,난방을 안해주셔서 춥게잤네요,2022.10.24,3
2,1000003240,white,minimal,ocean,3,영월2박3***,아이와 함께,방 깨끗합니다. 주변 산책하며 바닷가도 가까워 좋아요.\n아쉬운 점은 방에 욱풍이 ...,2024.11.27,4
3,1000003240,white,minimal,ocean,3,작은그*****,NaN,막 별로였던 건 아니지만 생각보다 세련된 느낌의 펜션은 아니었어요.\n그래도 원래 ...,2020.02.13,5
4,1000003240,white,minimal,ocean,4,초코렛이리*****,친구와 함께,바다와는 쪼금 거리가 있었지만 사장님이 친절했어요!\n주방용품은 다 잘 되어있었는데...,1일 전,5

In [33]:
df_merged1.to_csv('추천시스템감성분석용.csv', index=False)

In [14]:
df_merged1 = df_merged1.drop(columns=['리뷰내용', '작성일', '별점', '동반유형'])

In [15]:
df_merged1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 643843 entries, 0 to 643842
Data columns (total 6 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   숙소ID    643843 non-null  int64
 1   color   643843 non-null  object
 2   style   643843 non-null  object
 3   view    643843 non-null  object
 4   작성자     643843 non-null  object
 5   감성별점    643843 non-null  int64
dtypes: int64(2), object(4)
memory usage: 29.5+ MB

## 메인 프레임 상위,하위 시도 와 df_merged1 병합

In [16]:
df_메인.head()

,최초리뷰연도,최초리뷰월,숙소ID,숙소명,숙소유형코드,숙소운영형태,상위 시도,하위 시구,위도,경도,...,체크아웃시간,숙소 검색량(전체),지역별_유튜브Top20_평균조회수,주중판매가,주말판매가,판매가비율,리뷰수,별점,감성별점,종합평균점수
0,2017,11,23184,영등포라이프스타일FHOTEL,1,Motel,서울,영등포구,37.517182,126.911217,...,12:00,20,725000,65000,110000,1.7,3202,4.7,3.1,3.9
1,2017,12,23192,청주오창M+,1,Motel,충북,청주시,36.713884,127.439228,...,12:00,20,67961,55000,50000,0.9,670,4.6,3.8,4.2
2,2017,10,23197,강남렉시,1,Motel,서울,강남구,37.498792,127.033956,...,13:00,310,725000,60000,120000,2.0,9275,4.2,2.9,3.5
3,2017,12,23204,대전유성시나브로,1,Motel,대전,유성구,36.356873,127.349172,...,13:00,20,155050,60000,90000,1.5,245,4.7,4.1,4.4
4,2017,10,23207,역삼벤,1,Motel,서울,강남구,37.500706,127.039849,...,12:00,590,725000,55000,125000,2.3,10124,4.8,3.0,3.9

In [17]:
df_merged2 = pd.merge(df_merged1, df_메인[['숙소ID', '상위 시도', '하위 시구']], on='숙소ID', how='left')

In [18]:
df_merged2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 643843 entries, 0 to 643842
Data columns (total 8 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   숙소ID    643843 non-null  int64
 1   color   643843 non-null  object
 2   style   643843 non-null  object
 3   view    643843 non-null  object
 4   작성자     643843 non-null  object
 5   감성별점    643843 non-null  int64
 6   상위 시도   643843 non-null  object
 7   하위 시구   643843 non-null  object
dtypes: int64(2), object(6)
memory usage: 39.3+ MB

In [19]:
df_merged2['상위 시도'].value_counts()

상위 시도
경기    109074
서울     96481
강원     57776
경북     48258
경남     45769
부산     37849
충남     37628
제주     36366
인천     34668
전남     33771
전북     26842
충북     20527
대구     19316
울산     15953
광주     12416
대전     10765
세종       384
Name: count, dtype: int64

In [20]:
df_merged2['하위 시구'].value_counts()

하위 시구
중구     26061
제주시    24299
강릉시    14474
수원시    14207
여수시    14201
       ...
구좌읍       63
산내면       50
신안군       14
봉화군        8
전의면        6
Name: count, Length: 209, dtype: int64

In [21]:
df_merged2['시도'] = df_merged2['상위 시도'] + ' ' + df_merged2['하위 시구']

In [22]:
df_merged2 = df_merged2.drop(columns=['상위 시도', '하위 시구'])

https://place-site.yanolja.com/places/숙소ID?srpKeyword=숙소ID

In [23]:
# 숙소URL 컬럼 생성
url_base = "https://place-site.yanolja.com/places/{}?srpKeyword={}"
df_merged2['숙소URL'] = df_merged2['숙소ID'].apply(lambda x: url_base.format(x, x))
df_merged2[['숙소ID', '숙소URL']].head()

         숙소ID                                              숙소URL
0  1000003240  https://place-site.yanolja.com/places/10000032...
1  1000003240  https://place-site.yanolja.com/places/10000032...
2  1000003240  https://place-site.yanolja.com/places/10000032...
3  1000003240  https://place-site.yanolja.com/places/10000032...
4  1000003240  https://place-site.yanolja.com/places/10000032...

In [24]:
df_merged2

,숙소ID,color,style,view,작성자,감성별점,시도,숙소URL
0,1000003240,white,minimal,ocean,니제*,1,강원 속초시,https://place-site.yanolja.com/places/10000032...
1,1000003240,white,minimal,ocean,브뤼셀*****,3,강원 속초시,https://place-site.yanolja.com/places/10000032...
2,1000003240,white,minimal,ocean,영월2박3***,4,강원 속초시,https://place-site.yanolja.com/places/10000032...
3,1000003240,white,minimal,ocean,작은그*****,5,강원 속초시,https://place-site.yanolja.com/places/10000032...
4,1000003240,white,minimal,ocean,초코렛이리*****,5,강원 속초시,https://place-site.yanolja.com/places/10000032...
...,...,...,...,...,...,...,...,...
643838,3020735,white,minimal,other,으니062*,3,인천 강화군,https://place-site.yanolja.com/places/3020735?...
643839,3020735,white,minimal,other,바스크조약***,5,인천 강화군,https://place-site.yanolja.com/places/3020735?...
643840,3020735,white,minimal,other,sis79**,5,인천 강화군,https://place-site.yanolja.com/places/3020735?...
643841,3020735,white,minimal,other,알파고사랑*******,5,인천 강화군,https://place-site.yanolja.com/places/3020735?...
643842,3020735,white,minimal,other,귀염둥이그*******,5,인천 강화군,https://place-site.yanolja.com/places/3020735?...

In [25]:
df_merged2.to_csv('추천시스템.csv', index=False)
df_merged2

,숙소ID,color,style,view,작성자,감성별점,시도,숙소URL
0,1000003240,white,minimal,ocean,니제*,1,강원 속초시,https://place-site.yanolja.com/places/10000032...
1,1000003240,white,minimal,ocean,브뤼셀*****,3,강원 속초시,https://place-site.yanolja.com/places/10000032...
2,1000003240,white,minimal,ocean,영월2박3***,4,강원 속초시,https://place-site.yanolja.com/places/10000032...
3,1000003240,white,minimal,ocean,작은그*****,5,강원 속초시,https://place-site.yanolja.com/places/10000032...
4,1000003240,white,minimal,ocean,초코렛이리*****,5,강원 속초시,https://place-site.yanolja.com/places/10000032...
...,...,...,...,...,...,...,...,...
643838,3020735,white,minimal,other,으니062*,3,인천 강화군,https://place-site.yanolja.com/places/3020735?...
643839,3020735,white,minimal,other,바스크조약***,5,인천 강화군,https://place-site.yanolja.com/places/3020735?...
643840,3020735,white,minimal,other,sis79**,5,인천 강화군,https://place-site.yanolja.com/places/3020735?...
643841,3020735,white,minimal,other,알파고사랑*******,5,인천 강화군,https://place-site.yanolja.com/places/3020735?...
643842,3020735,white,minimal,other,귀염둥이그*******,5,인천 강화군,https://place-site.yanolja.com/places/3020735?...

# wix api 호출

In [ ]:
import requests
import pandas as pd
BASE = "wix_url"
params = {
    "limit": "5"
}
r = requests.get(BASE, params=params, timeout=20)
r.raise_for_status()
payload = r.json()
items = payload.get("items", [])
cursor = payload.get("nextCursor")
df = pd.DataFrame(items)
df.to_csv("selections_dump.csv", index=False, encoding="utf-8-sig")
df

,_publishDate,updatedAt,email,style,_id,_owner,_createdDate,_updatedDate,_publishStatus,region,tone,userId,leisure,view
0,2025-08-26T05:35:10.879Z,2025-08-26T05:35:10.588Z,확인용,Minimal,297c53d0-51be-4f6b-a019-8561434fdb4f,ece25cd7-3941-4646-9c74-f7b93e1d3b06,2025-08-26T05:35:10.879Z,2025-08-26T05:35:10.879Z,PUBLISHED,경기도 가평,Dark,확인용,[국내레저],Other
1,2025-08-26T05:26:25.932Z,2025-08-26T05:26:25.635Z,sy353600@naver.com,Minimal,4da66a64-611a-4497-9bc8-2f85bb9744c5,3e248562-9ca0-4605-8a53-92aaa7a6972e,2025-08-26T05:26:25.931Z,2025-08-26T05:26:25.931Z,PUBLISHED,경기도 용인시,White,sy353600@naver.com,[국내레저],City
2,2025-08-26T05:22:31.411Z,2025-08-26T05:22:31.122Z,이유빈,Classic,5bd85824-9e55-45c5-8cb9-d5fbc6311d33,ece25cd7-3941-4646-9c74-f7b93e1d3b06,2025-08-26T05:22:31.411Z,2025-08-26T05:22:31.411Z,PUBLISHED,서울,White,이유빈,[공연/전시],Ocean
3,2025-08-26T04:05:52.382Z,2025-08-26T04:05:52.083Z,user@example.com,Luxury,18487132-6b3d-4b15-b64d-a6a49e0776bc,5b33d955-eb76-4222-8a94-7d3b4e4c1af5,2025-08-26T04:05:52.382Z,2025-08-26T04:05:52.382Z,PUBLISHED,서울 강남구,Modern,abc-123,"[스파, 수영장]",City
4,2025-08-26T03:44:52.762Z,2025-08-26T03:44:57.975Z,sy@naver,Wood,acbabab0-9a3b-4eb9-bd2c-49a292c925b2,3e248562-9ca0-4605-8a53-92aaa7a6972e,2025-08-26T03:44:52.761Z,2025-08-26T03:44:58.194Z,PUBLISHED,서울,White,sy@naver,[],Ocean

## 필요한 컬럼만 api 호출

In [ ]:
import requests
import pandas as pd

WIX_API_URL = "wix_url"
query_params = {
    "limit": "5"
}
response = requests.get(WIX_API_URL, params=query_params, timeout=20)
response.raise_for_status()
result_json = response.json()

selection_items = result_json.get("items", [])
next_cursor = result_json.get("nextCursor")

# DataFrame 생성
df_selections = pd.DataFrame(selection_items)

# 필요한 컬럼만 추출 및 순서 지정
selection_columns = ["email", "region", "tone", "style", "view", "leisure"]
df_selections = df_selections[selection_columns]

# CSV 저장
df_selections.to_csv("wix_selections.csv", index=False, encoding="utf-8-sig")

df_selections

                   email   region    tone    style   view    leisure
0  bella953038@gmail.com       서울    Warm     Wood  Ocean     [국내레저]
1                    확인용   경기도 가평    Dark  Minimal  Other     [국내레저]
2     sy353600@naver.com  경기도 용인시   White  Minimal   City     [국내레저]
3                    이유빈       서울   White  Classic  Ocean    [공연/전시]
4       user@example.com   서울 강남구  Modern   Luxury   City  [스파, 수영장]

- wix 데이터 프레임에 랜덤으로 ID 부여

In [ ]:
import requests
import pandas as pd
import random
import hashlib

WIX_API_URL = "wix_Url"
query_params = {
    "limit": "5"
}
response = requests.get(WIX_API_URL, params=query_params, timeout=20)
response.raise_for_status()
result_json = response.json()

selection_items = result_json.get("items", [])
next_cursor = result_json.get("nextCursor")

# DataFrame 생성
df_selections = pd.DataFrame(selection_items)

# 필요한 컬럼만 추출 및 순서 지정
selection_columns = ["email", "region", "tone", "style", "view", "leisure"]
df_selections = df_selections[selection_columns]

# ---------------------- 추가 부분 ----------------------
# 추천시스템.csv 불러오기 (작성자 ID 활용)
df_추천DB = pd.read_csv("추천시스템.csv")

# 이메일 해시값을 기반으로 항상 같은 작성자 ID를 반환하는 함수
def assign_fixed_author(email, df_authors):
    author_list = df_authors['작성자'].unique()
    # 이메일을 해시 → 정수 변환 → 인덱스 선택
    seed = int(hashlib.sha256(str(email).encode('utf-8')).hexdigest(), 16)
    idx = seed % len(author_list)
    return author_list[idx]

# df_selections에 가상 작성자 매핑 추가
df_selections['작성자'] = df_selections['email'].apply(
    lambda x: assign_fixed_author(x, df_추천DB)
)
# -------------------------------------------------------

# # CSV 저장
df_selections.to_csv("wix_selections.csv", index=False, encoding="utf-8-sig")

df_selections

,email,region,tone,style,view,leisure,작성자
0,1111,강남,Dark,Wood,City,[국내레저],구름같이가*****
1,bella953038@gmail.com,경기,Dark,Modern,Mountain,[국내레저],그기가*
2,이유빈,서율,Dark,Wood,City,[국내레저],조각구름상******
3,확인용,경기도 가평,Dark,Minimal,Other,[국내레저],창경궁댄서**
4,sy353600@naver.com,경기도 용인시,White,Minimal,City,[국내레저],syddd***

# 추천 시스템 모델 확인

## 추천 시스템 피클파일로 모델로드

## 추천 프레임 정제 및 컬럼 추가

In [4]:
import pandas as pd

df_추천 = pd.read_csv("추천시스템감성분석용_완.csv")
df_main = pd.read_csv('../프로젝트/0814_메인프레임v13.csv')

In [6]:
df_추천

,숙소ID,color,style,view,별점,작성자,동반유형,리뷰내용,작성일,감성별점
0,1000003240,white,minimal,ocean,1,니제*,NaN,"바다 안보임, 테라스 금연, 식수 없음, 객실 청결상태 안좋음, 드라이도 사용하기 ...",2022.10.02,1
1,1000003240,white,minimal,ocean,2,브뤼셀*****,NaN,난방을 안해주셔서 춥게잤네요,2022.10.24,2
2,1000003240,white,minimal,ocean,3,영월2박3***,아이와 함께,방 깨끗합니다. 주변 산책하며 바닷가도 가까워 좋아요.\n아쉬운 점은 방에 욱풍이 ...,2024.11.27,4
3,1000003240,white,minimal,ocean,3,작은그*****,NaN,막 별로였던 건 아니지만 생각보다 세련된 느낌의 펜션은 아니었어요.\n그래도 원래 ...,2020.02.13,5
4,1000003240,white,minimal,ocean,4,초코렛이리*****,친구와 함께,바다와는 쪼금 거리가 있었지만 사장님이 친절했어요!\n주방용품은 다 잘 되어있었는데...,1일 전,5
...,...,...,...,...,...,...,...,...,...,...
643838,3020735,white,minimal,other,5,으니062*,NaN,머무는 동안 즐거웠습니다 ♡,2023.10.02,3
643839,3020735,white,minimal,other,5,바스크조약***,NaN,입실하기 전부터 강화도 날씨 안내 겸 웰컴 문자를 보내주시고 편하고 재밌게 잘 쉬고...,2023.10.02,5
643840,3020735,white,minimal,other,5,sis79**,NaN,좋습니다ㅎ,2023.09.30,5
643841,3020735,white,minimal,other,5,알파고사랑*******,NaN,침대 매트리스에 긴머리카락 수두룩~~\n사장님이 넘 친절하셔서 좋앗다.\n그이상...,2023.09.29,5
643842,3020735,white,minimal,other,5,귀염둥이그*******,NaN,너무 깨끗하고 사장님 진짜 짱♡,2023.09.24,5

In [7]:
df_main.head()

,최초리뷰연도,최초리뷰월,숙소ID,숙소명,숙소유형코드,숙소운영형태,상위 시도,하위 시구,위도,경도,...,체크아웃시간,숙소 검색량(전체),지역별_유튜브Top20_평균조회수,주중판매가,주말판매가,판매가비율,리뷰수,별점,감성별점,종합평균점수
0,2017,11,23184,영등포라이프스타일FHOTEL,1,Motel,서울,영등포구,37.517182,126.911217,...,12:00,20,725000,65000,110000,1.7,3202,4.7,3.1,3.9
1,2017,12,23192,청주오창M+,1,Motel,충북,청주시,36.713884,127.439228,...,12:00,20,67961,55000,50000,0.9,670,4.6,3.8,4.2
2,2017,10,23197,강남렉시,1,Motel,서울,강남구,37.498792,127.033956,...,13:00,310,725000,60000,120000,2.0,9275,4.2,2.9,3.5
3,2017,12,23204,대전유성시나브로,1,Motel,대전,유성구,36.356873,127.349172,...,13:00,20,155050,60000,90000,1.5,245,4.7,4.1,4.4
4,2017,10,23207,역삼벤,1,Motel,서울,강남구,37.500706,127.039849,...,12:00,590,725000,55000,125000,2.3,10124,4.8,3.0,3.9

In [8]:
# 병합 (df_추천 기준으로만 남김)
df_추천프레임 = df_추천.merge(
    df_main[['숙소ID', '숙소명', '숙소운영형태']],
    on='숙소ID',
    how='left'   # df_추천 기준
)

# 결과 확인
df_추천프레임

,숙소ID,color,style,view,별점,작성자,동반유형,리뷰내용,작성일,감성별점,숙소명,숙소운영형태
0,1000003240,white,minimal,ocean,1,니제*,NaN,"바다 안보임, 테라스 금연, 식수 없음, 객실 청결상태 안좋음, 드라이도 사용하기 ...",2022.10.02,1,속초하늘바다펜션,Pension
1,1000003240,white,minimal,ocean,2,브뤼셀*****,NaN,난방을 안해주셔서 춥게잤네요,2022.10.24,2,속초하늘바다펜션,Pension
2,1000003240,white,minimal,ocean,3,영월2박3***,아이와 함께,방 깨끗합니다. 주변 산책하며 바닷가도 가까워 좋아요.\n아쉬운 점은 방에 욱풍이 ...,2024.11.27,4,속초하늘바다펜션,Pension
3,1000003240,white,minimal,ocean,3,작은그*****,NaN,막 별로였던 건 아니지만 생각보다 세련된 느낌의 펜션은 아니었어요.\n그래도 원래 ...,2020.02.13,5,속초하늘바다펜션,Pension
4,1000003240,white,minimal,ocean,4,초코렛이리*****,친구와 함께,바다와는 쪼금 거리가 있었지만 사장님이 친절했어요!\n주방용품은 다 잘 되어있었는데...,1일 전,5,속초하늘바다펜션,Pension
...,...,...,...,...,...,...,...,...,...,...,...,...
643838,3020735,white,minimal,other,5,으니062*,NaN,머무는 동안 즐거웠습니다 ♡,2023.10.02,3,강화도수에뇨펜션,Pension
643839,3020735,white,minimal,other,5,바스크조약***,NaN,입실하기 전부터 강화도 날씨 안내 겸 웰컴 문자를 보내주시고 편하고 재밌게 잘 쉬고...,2023.10.02,5,강화도수에뇨펜션,Pension
643840,3020735,white,minimal,other,5,sis79**,NaN,좋습니다ㅎ,2023.09.30,5,강화도수에뇨펜션,Pension
643841,3020735,white,minimal,other,5,알파고사랑*******,NaN,침대 매트리스에 긴머리카락 수두룩~~\n사장님이 넘 친절하셔서 좋앗다.\n그이상...,2023.09.29,5,강화도수에뇨펜션,Pension
643842,3020735,white,minimal,other,5,귀염둥이그*******,NaN,너무 깨끗하고 사장님 진짜 짱♡,2023.09.24,5,강화도수에뇨펜션,Pension

In [10]:
df_추천프레임.head()

,숙소ID,color,style,view,별점,작성자,동반유형,리뷰내용,작성일,감성별점,숙소명,숙소운영형태
0,1000003240,white,minimal,ocean,1,니제*,NaN,"바다 안보임, 테라스 금연, 식수 없음, 객실 청결상태 안좋음, 드라이도 사용하기 ...",2022.10.02,1,속초하늘바다펜션,Pension
1,1000003240,white,minimal,ocean,2,브뤼셀*****,NaN,난방을 안해주셔서 춥게잤네요,2022.10.24,2,속초하늘바다펜션,Pension
2,1000003240,white,minimal,ocean,3,영월2박3***,아이와 함께,방 깨끗합니다. 주변 산책하며 바닷가도 가까워 좋아요.\n아쉬운 점은 방에 욱풍이 ...,2024.11.27,4,속초하늘바다펜션,Pension
3,1000003240,white,minimal,ocean,3,작은그*****,NaN,막 별로였던 건 아니지만 생각보다 세련된 느낌의 펜션은 아니었어요.\n그래도 원래 ...,2020.02.13,5,속초하늘바다펜션,Pension
4,1000003240,white,minimal,ocean,4,초코렛이리*****,친구와 함께,바다와는 쪼금 거리가 있었지만 사장님이 친절했어요!\n주방용품은 다 잘 되어있었는데...,1일 전,5,속초하늘바다펜션,Pension

In [11]:
# df_추천프레임에 df_추천clean에있는 숙소URL, 시도	컬럼 숙소ID 기준으로 추가
df_추천프레임 = df_추천프레임.merge(
    df_추천clean[['숙소ID', '숙소URL', '시도']],
    on='숙소ID',
    how='left'   # df_추천프레임 기준
)

In [12]:
df_추천프레임

,숙소ID,color,style,view,별점,작성자,동반유형,리뷰내용,작성일,감성별점,숙소명,숙소운영형태,숙소URL,시도
0,1000003240,white,minimal,ocean,1,니제*,NaN,"바다 안보임, 테라스 금연, 식수 없음, 객실 청결상태 안좋음, 드라이도 사용하기 ...",2022.10.02,1,속초하늘바다펜션,Pension,https://place-site.yanolja.com/places/10000032...,강원 속초시
1,1000003240,white,minimal,ocean,2,브뤼셀*****,NaN,난방을 안해주셔서 춥게잤네요,2022.10.24,2,속초하늘바다펜션,Pension,https://place-site.yanolja.com/places/10000032...,강원 속초시
2,1000003240,white,minimal,ocean,3,영월2박3***,아이와 함께,방 깨끗합니다. 주변 산책하며 바닷가도 가까워 좋아요.\n아쉬운 점은 방에 욱풍이 ...,2024.11.27,4,속초하늘바다펜션,Pension,https://place-site.yanolja.com/places/10000032...,강원 속초시
3,1000003240,white,minimal,ocean,3,작은그*****,NaN,막 별로였던 건 아니지만 생각보다 세련된 느낌의 펜션은 아니었어요.\n그래도 원래 ...,2020.02.13,5,속초하늘바다펜션,Pension,https://place-site.yanolja.com/places/10000032...,강원 속초시
4,1000003240,white,minimal,ocean,4,초코렛이리*****,친구와 함께,바다와는 쪼금 거리가 있었지만 사장님이 친절했어요!\n주방용품은 다 잘 되어있었는데...,1일 전,5,속초하늘바다펜션,Pension,https://place-site.yanolja.com/places/10000032...,강원 속초시
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
643838,3020735,white,minimal,other,5,으니062*,NaN,머무는 동안 즐거웠습니다 ♡,2023.10.02,3,강화도수에뇨펜션,Pension,https://place-site.yanolja.com/places/3020735?...,인천 강화군
643839,3020735,white,minimal,other,5,바스크조약***,NaN,입실하기 전부터 강화도 날씨 안내 겸 웰컴 문자를 보내주시고 편하고 재밌게 잘 쉬고...,2023.10.02,5,강화도수에뇨펜션,Pension,https://place-site.yanolja.com/places/3020735?...,인천 강화군
643840,3020735,white,minimal,other,5,sis79**,NaN,좋습니다ㅎ,2023.09.30,5,강화도수에뇨펜션,Pension,https://place-site.yanolja.com/places/3020735?...,인천 강화군
643841,3020735,white,minimal,other,5,알파고사랑*******,NaN,침대 매트리스에 긴머리카락 수두룩~~\n사장님이 넘 친절하셔서 좋앗다.\n그이상...,2023.09.29,5,강화도수에뇨펜션,Pension,https://place-site.yanolja.com/places/3020735?...,인천 강화군
643842,3020735,white,minimal,other,5,귀염둥이그*******,NaN,너무 깨끗하고 사장님 진짜 짱♡,2023.09.24,5,강화도수에뇨펜션,Pension,https://place-site.yanolja.com/places/3020735?...,인천 강화군

- 불필요한 컬럼 삭제

In [13]:
# 별점, 동반유형, 리뷰내용, 작성일, 숙소운영형태은 삭제
df_최종_추천프레임 = df_추천프레임.drop(columns=['별점', '동반유형', '리뷰내용', '작성일', '숙소운영형태'])

In [15]:
df_최종_추천프레임['감성별점'].value_counts()

감성별점
5    286478
1    141404
4    134349
3     59304
2     22308
Name: count, dtype: int64

In [16]:
df_최종_추천프레임.to_csv('최종_추천시스템0828.csv', index=False)

#  추천시스템

In [11]:
import pandas as pd

df_추천0827 = pd.read_csv('추천시스템0827.csv')
df_추천0827.head()

,숙소ID,color,style,view,작성자,감성별점,시도,숙소URL,숙소명,숙소운영형태
0,1000003240,white,minimal,ocean,니제*,1,강원 속초시,https://place-site.yanolja.com/places/10000032...,속초하늘바다펜션,Pension
1,1000003240,white,minimal,ocean,브뤼셀*****,3,강원 속초시,https://place-site.yanolja.com/places/10000032...,속초하늘바다펜션,Pension
2,1000003240,white,minimal,ocean,영월2박3***,4,강원 속초시,https://place-site.yanolja.com/places/10000032...,속초하늘바다펜션,Pension
3,1000003240,white,minimal,ocean,작은그*****,5,강원 속초시,https://place-site.yanolja.com/places/10000032...,속초하늘바다펜션,Pension
4,1000003240,white,minimal,ocean,초코렛이리*****,5,강원 속초시,https://place-site.yanolja.com/places/10000032...,속초하늘바다펜션,Pension

- 불필요한 컬럼은 삭제

In [12]:
# df_추천0827 감성별점, 작성자 컬럼 삭제
df_추천clean = df_추천0827.drop(columns=['감성별점', '작성자'], errors='ignore')

- 숙소ID 기준으로 중복값 삭제

In [13]:
# 숙소ID 기준으로 중복값 삭제
df_추천clean = df_추천clean.drop_duplicates(subset='숙소ID').reset_index(drop=True)

In [14]:
df_추천clean.to_csv('추천숙소정보.csv', index=False)

In [2]:
import pandas as pd

df_추천clean = pd.read_csv('추천숙소정보.csv')

## wix api 호출

In [ ]:
import requests
import pandas as pd
import random
import hashlib

WIX_API_URL = "wix_Url"
query_params = {
    "limit": "5"
}
response = requests.get(WIX_API_URL, params=query_params, timeout=20)
response.raise_for_status()
result_json = response.json()

selection_items = result_json.get("items", [])
next_cursor = result_json.get("nextCursor")

# DataFrame 생성
df_selections = pd.DataFrame(selection_items)

# 필요한 컬럼만 추출 및 순서 지정
selection_columns = ["email", "region", "tone", "style", "view", "leisure"]
df_selections = df_selections[selection_columns]

# ---------------------- 추가 부분 ----------------------
# 추천시스템.csv 불러오기 (작성자 ID 활용)
df_추천DB = df_추천0827.copy()

# 이메일 해시값을 기반으로 항상 같은 작성자 ID를 반환하는 함수
def assign_fixed_author(email, df_authors):
    author_list = df_authors['작성자'].unique()
    # 이메일을 해시 → 정수 변환 → 인덱스 선택
    seed = int(hashlib.sha256(str(email).encode('utf-8')).hexdigest(), 16)
    idx = seed % len(author_list)
    return author_list[idx]

# df_selections에 가상 작성자 매핑 추가
df_selections['작성자'] = df_selections['email'].apply(
    lambda x: assign_fixed_author(x, df_추천DB)
)
# -------------------------------------------------------

# # CSV 저장
df_selections.to_csv("wix_selections.csv", index=False, encoding="utf-8-sig")

df_selections

,email,region,tone,style,view,leisure,작성자
0,1111,강남,Dark,Wood,City,[국내레저],구름같이가*****
1,bella953038@gmail.com,경기,Dark,Modern,Mountain,[국내레저],그기가*
2,이유빈,서율,Dark,Wood,City,[국내레저],조각구름상******
3,확인용,경기도 가평,Dark,Minimal,Other,[국내레저],창경궁댄서**
4,sy353600@naver.com,경기도 용인시,White,Minimal,City,[국내레저],syddd***

## 모델 수정전 서프라이즈 모델

In [8]:
import joblib

# 저장된 모델 로드
loaded_svd = joblib.load('best_svd_model.joblib')

def recommend_top_n(df_selections, loaded_svd, user_index, n=150):
    # 사용자 ID 추출
    user_id = df_selections.iloc[user_index]['작성자']
    # 사용자가 이미 평가한 숙소ID 리스트
    rated_accommodations = df_추천0827.loc[df_추천0827['작성자'] == user_id, '숙소ID'].tolist()
    # 전체 숙소ID 리스트
    all_accommodations = df_추천0827['숙소ID'].unique()
    # 평가하지 않은 숙소ID 리스트
    unrated_accommodations = [item for item in all_accommodations if item not in rated_accommodations]

    predictions = []
    for accommodation_id in unrated_accommodations:
        predicted_rating = loaded_svd.predict(str(user_id), str(accommodation_id))
        predictions.append(predicted_rating)

    predictions.sort(key=lambda x: x.est, reverse=True)
    top_n_recommendations = predictions[:n]

    print(f"\n{user_id} 님에게 추천하는 숙소 TOP {n}:")
    for i, pred in enumerate(top_n_recommendations):
        print(f"{i+1}위: 숙소ID {pred.iid} - 예상 평점: {pred.est}")


        
    top_n_ids = [str(p.iid) for p in top_n_recommendations]        # 순서 유지용 ID 리스트
    score_map = {str(p.iid): float(p.est) for p in top_n_recommendations}  # 예측 점수 매핑
    return top_n_ids, score_map

top_n_ids, score_map = recommend_top_n(df_selections, loaded_svd, user_index=1, n=150)

그기가* 님에게 추천하는 숙소 TOP 150:
1위: 숙소ID 1000094308 - 예상 평점: 5
2위: 숙소ID 3013510 - 예상 평점: 5
3위: 숙소ID 3002268 - 예상 평점: 4.998526137323962
4위: 숙소ID 3013225 - 예상 평점: 4.97518316055184
5위: 숙소ID 1000109921 - 예상 평점: 4.973256930672971
6위: 숙소ID 3016779 - 예상 평점: 4.9679188443131075
7위: 숙소ID 3018354 - 예상 평점: 4.960732384834977
8위: 숙소ID 3014225 - 예상 평점: 4.952244138087783
9위: 숙소ID 1000111899 - 예상 평점: 4.948719069423138
10위: 숙소ID 3013096 - 예상 평점: 4.939930879125759
11위: 숙소ID 10041674 - 예상 평점: 4.92181633423065
12위: 숙소ID 10044478 - 예상 평점: 4.9119793130033305
13위: 숙소ID 1000092412 - 예상 평점: 4.901385741232071
14위: 숙소ID 3014787 - 예상 평점: 4.899774799920862
15위: 숙소ID 10042877 - 예상 평점: 4.887708024791005
16위: 숙소ID 1000101965 - 예상 평점: 4.876977967702178
17위: 숙소ID 1000109516 - 예상 평점: 4.873406138903296
18위: 숙소ID 3011684 - 예상 평점: 4.871629954112827
19위: 숙소ID 1000108346 - 예상 평점: 4.8703387059402745
20위: 숙소ID 10041617 - 예상 평점: 4.870051063123171
21위: 숙소ID 1000104309 - 예상 평점: 4.867069097768324
22위: 숙소ID 10039510 - 예상 평점: 4.866703904317719
23위: 숙소ID 3014370 - 예상 평점: 4.866277431587496
24위: 숙소ID 10040201 - 예상 평점: 4.866028262534819
25위: 숙소ID 1000105745 - 예상 평점: 4.865597037001862
26위: 숙소ID 10040444 - 예상 평점: 4.864767751035128
27위: 숙소ID 10043412 - 예상 평점: 4.857915595643308
28위: 숙소ID 3020435 - 예상 평점: 4.857598783646141
29위: 숙소ID 1000091722 - 예상 평점: 4.850724349753351
30위: 숙소ID 10039349 - 예상 평점: 4.848524214157478
31위: 숙소ID 10048782 - 예상 평점: 4.846985878099772
32위: 숙소ID 3014130 - 예상 평점: 4.845676582835523
33위: 숙소ID 3016494 - 예상 평점: 4.845477027474008
34위: 숙소ID 1000100687 - 예상 평점: 4.843792204701508
35위: 숙소ID 10056385 - 예상 평점: 4.843249645390785
36위: 숙소ID 1000092731 - 예상 평점: 4.842910500670095
37위: 숙소ID 10056792 - 예상 평점: 4.841428252440514
38위: 숙소ID 10046461 - 예상 평점: 4.840949302206171
39위: 숙소ID 3016387 - 예상 평점: 4.840606447510575
40위: 숙소ID 3009569 - 예상 평점: 4.840463791751195
41위: 숙소ID 1000105195 - 예상 평점: 4.840225896887607
42위: 숙소ID 10059249 - 예상 평점: 4.839635898307374
43위: 숙소ID 1000108356 - 예상 평점: 4.8393654239193395
44위: 숙소ID 1000110965 - 예상 평점: 4.838605326212585
45위: 숙소ID 1000109519 - 예상 평점: 4.837649605753354
46위: 숙소ID 1000104239 - 예상 평점: 4.836007813617003
47위: 숙소ID 1000092497 - 예상 평점: 4.8359800559021675
48위: 숙소ID 3018248 - 예상 평점: 4.834992119144067
49위: 숙소ID 10044446 - 예상 평점: 4.834695924623652
50위: 숙소ID 1000091642 - 예상 평점: 4.8287875329973735
51위: 숙소ID 1000104912 - 예상 평점: 4.8280436428585
52위: 숙소ID 3010985 - 예상 평점: 4.826807756054753
53위: 숙소ID 3015605 - 예상 평점: 4.82677628331022
54위: 숙소ID 10060690 - 예상 평점: 4.826097364396507
55위: 숙소ID 1000114338 - 예상 평점: 4.823673892828076
56위: 숙소ID 1000090001 - 예상 평점: 4.822020473053157
57위: 숙소ID 10058349 - 예상 평점: 4.821739432500619
58위: 숙소ID 10039508 - 예상 평점: 4.820870214436725
59위: 숙소ID 10052014 - 예상 평점: 4.819340907731498
60위: 숙소ID 1000104896 - 예상 평점: 4.819146890953294
61위: 숙소ID 1000110054 - 예상 평점: 4.818116601646118
62위: 숙소ID 25295 - 예상 평점: 4.817538916728728
63위: 숙소ID 1000112037 - 예상 평점: 4.817477600997042
64위: 숙소ID 1000090682 - 예상 평점: 4.815456367375794
65위: 숙소ID 10052878 - 예상 평점: 4.814670734890066
66위: 숙소ID 1000104182 - 예상 평점: 4.8129211840047725
67위: 숙소ID 10042498 - 예상 평점: 4.811439564906454
68위: 숙소ID 3011667 - 예상 평점: 4.811097173561822
69위: 숙소ID 1000108285 - 예상 평점: 4.810006083748848
70위: 숙소ID 1000109257 - 예상 평점: 4.809648089075163
71위: 숙소ID 10039577 - 예상 평점: 4.808109820386687
72위: 숙소ID 1000113771 - 예상 평점: 4.805625085358744
73위: 숙소ID 1000108697 - 예상 평점: 4.8050191650343725
74위: 숙소ID 10052182 - 예상 평점: 4.8048634570357285
75위: 숙소ID 1000100216 - 예상 평점: 4.803869078412554
76위: 숙소ID 3011994 - 예상 평점: 4.800653734890635
77위: 숙소ID 1000100665 - 예상 평점: 4.800636156515819
78위: 숙소ID 1000104903 - 예상 평점: 4.800333473207046
79위: 숙소ID 10060267 - 예상 평점: 4.796762193246063
80위: 숙소ID 1000112803 - 예상 평점: 4.7953249501377435
81위: 숙소ID 10052845 - 예상 평점: 4.794409366792181
82위: 숙소ID 10042378 - 예상 평점: 4.79374312364333
83위: 숙소ID 3013509 - 예상 평점: 4.792911047585278
84위: 숙소ID 1000109424 - 예상 평점: 4.791128104402672
85위: 숙소ID 1000111103 - 예상 평점: 4.790815120562578
86위: 숙소ID 3018285 - 예상 평점: 4.79044596163446
87위: 숙소ID 3014676 - 예상 평점: 4.789998582840254
88위: 숙소ID 10055906 - 예상 평점: 4.789620909261602
89위: 숙소ID 10046872 - 예상 평점: 4.788915986316534
90위: 숙소ID 3008635 - 예상 평점: 4.788712012573943
91위: 숙소ID 3015532 - 예상 평점: 4.7883966953896415
92위: 숙소ID 3015944 - 예상 평점: 4.787907609402533
93위: 숙소ID 1000111479 - 예상 평점: 4.7873210567045446
94위: 숙소ID 3005652 - 예상 평점: 4.78679707138728
95위: 숙소ID 10044607 - 예상 평점: 4.785876593995091
96위: 숙소ID 1000108885 - 예상 평점: 4.7849638577075035
97위: 숙소ID 3012271 - 예상 평점: 4.784588226622055
98위: 숙소ID 10040489 - 예상 평점: 4.783116909605444
99위: 숙소ID 1000113665 - 예상 평점: 4.7830597485455915
100위: 숙소ID 1000099369 - 예상 평점: 4.782696757532548
101위: 숙소ID 1000101223 - 예상 평점: 4.781814937469417
102위: 숙소ID 10048293 - 예상 평점: 4.781068319193325
103위: 숙소ID 10057618 - 예상 평점: 4.780581703374618
104위: 숙소ID 10042785 - 예상 평점: 4.780408480943499
105위: 숙소ID 3010266 - 예상 평점: 4.7797130543621735
106위: 숙소ID 3006331 - 예상 평점: 4.7789859718945396
107위: 숙소ID 3012481 - 예상 평점: 4.778407931877262
108위: 숙소ID 10060979 - 예상 평점: 4.777936576016478
109위: 숙소ID 10054442 - 예상 평점: 4.777901141678112
110위: 숙소ID 1000113387 - 예상 평점: 4.776875217473963
111위: 숙소ID 3016971 - 예상 평점: 4.775578236806352
112위: 숙소ID 10045439 - 예상 평점: 4.7735204709098475
113위: 숙소ID 1000108458 - 예상 평점: 4.772293041839194
114위: 숙소ID 10056346 - 예상 평점: 4.771686004587746
115위: 숙소ID 1000108946 - 예상 평점: 4.771484215276049
116위: 숙소ID 3016831 - 예상 평점: 4.770571866483473
117위: 숙소ID 10043679 - 예상 평점: 4.769268599239526
118위: 숙소ID 1000104416 - 예상 평점: 4.766982243918517
119위: 숙소ID 1000109019 - 예상 평점: 4.765929472048364
120위: 숙소ID 3016367 - 예상 평점: 4.765319726353475
121위: 숙소ID 1000110142 - 예상 평점: 4.7648052483289955
122위: 숙소ID 10046056 - 예상 평점: 4.764769187043543
123위: 숙소ID 10051821 - 예상 평점: 4.762476383831835
124위: 숙소ID 3010529 - 예상 평점: 4.761043771719987
125위: 숙소ID 3013294 - 예상 평점: 4.758975615214388
126위: 숙소ID 3013802 - 예상 평점: 4.7587460687409875
127위: 숙소ID 10043827 - 예상 평점: 4.754924640794604
128위: 숙소ID 10044572 - 예상 평점: 4.753748022306979
129위: 숙소ID 1000104986 - 예상 평점: 4.753382210617639
130위: 숙소ID 10042545 - 예상 평점: 4.752077998167749
131위: 숙소ID 1000101993 - 예상 평점: 4.751201183895236
132위: 숙소ID 10055927 - 예상 평점: 4.750651268424007
133위: 숙소ID 3011813 - 예상 평점: 4.7505943598675655
134위: 숙소ID 1000105000 - 예상 평점: 4.750131739630203
135위: 숙소ID 1000111546 - 예상 평점: 4.748398011560894
136위: 숙소ID 3013519 - 예상 평점: 4.748236242473688
137위: 숙소ID 10042536 - 예상 평점: 4.747998099767433
138위: 숙소ID 24981 - 예상 평점: 4.747580011548061
139위: 숙소ID 10048356 - 예상 평점: 4.746721619515104
140위: 숙소ID 10048707 - 예상 평점: 4.746445757622363
141위: 숙소ID 1000109696 - 예상 평점: 4.746300710987659
142위: 숙소ID 3006448 - 예상 평점: 4.746203825794939
143위: 숙소ID 1000088802 - 예상 평점: 4.746118554065055
144위: 숙소ID 10041169 - 예상 평점: 4.746049946405865
145위: 숙소ID 1000111264 - 예상 평점: 4.7451812828548325
146위: 숙소ID 10045672 - 예상 평점: 4.744303364640054
147위: 숙소ID 1000110371 - 예상 평점: 4.744289711747939
148위: 숙소ID 10052651 - 예상 평점: 4.74409335959919
149위: 숙소ID 3014552 - 예상 평점: 4.744018286447975
150위: 숙소ID 1000091354 - 예상 평점: 4.743159177327798

In [9]:
recommend_df = (
    df_추천clean.copy()
      .assign(숙소ID=lambda d: d['숙소ID'].astype(str))
      .set_index('숙소ID')
      .reindex(top_n_ids)   # top_n_ids 순서대로 정렬됨
      .reset_index()
)
recommend_df['예상평점'] = recommend_df['숙소ID'].map(score_map)
recommend_df

,숙소ID,color,style,view,시도,숙소URL,숙소명,숙소운영형태,예상평점
0,1000094308,warm,wood,other,전북 전주시,https://place-site.yanolja.com/places/10000943...,전주꽃잠펜션,Pension,5.000000
1,3013510,warm,wood,mountain,강원 고성군,https://place-site.yanolja.com/places/3013510?...,고성왕곡휴펜션,Pension,5.000000
2,3002268,vivid colors,minimal,other,전북 전주시,https://place-site.yanolja.com/places/3002268?...,전주별빛궁한옥스테이,GuestHouse,4.998526
3,3013225,vivid colors,wood,mountain,충북 단양군,https://place-site.yanolja.com/places/3013225?...,단양풀꽃나무펜션,Pension,4.975183
4,1000109921,white,minimal,other,경기 가평군,https://place-site.yanolja.com/places/10001099...,가평아디엘풀빌라,Pension,4.973257
...,...,...,...,...,...,...,...,...,...
145,10045672,white,minimal,other,충남 태안군,https://place-site.yanolja.com/places/10045672...,태안(안면도)스테이4월7일펜션,Pension,4.744303
146,1000110371,white,modern,other,충남 보령시,https://place-site.yanolja.com/places/10001103...,보령(대천)카카오스토리펜션,Pension,4.744290
147,10052651,white,minimal,other,강원 고성군,https://place-site.yanolja.com/places/10052651...,고성(속초)스테이지풀빌라,Pension,4.744093
148,3014552,vivid colors,modern,other,경남 합천군,https://place-site.yanolja.com/places/3014552?...,합천글램핑스토리,Pension,4.744018
149,1000091354,warm,wood,other,강원 화천군,https://place-site.yanolja.com/places/10000913...,화천랜드펜션,Pension,4.743159

## 시도 분류

## 숙소 스타일 분류

In [10]:
def filter_recommend_by_user(df_selections, recommend_df, user_index=1):
    # 컬럼명 소문자로 통일
    df_selections = df_selections.rename(columns=lambda x: x.lower())
    recommend_df = recommend_df.rename(columns=lambda x: x.lower())
    
    # 사용자 선택값 추출
    user_row = df_selections.iloc[user_index]
    user_tone = str(user_row['tone']).lower()
    user_style = str(user_row['style']).lower()
    user_view = str(user_row['view']).lower()
    
    # 추천 숙소에서 tone, style, view 모두 일치하는 것만 추출
    filtered = recommend_df[
        (recommend_df['color'].str.lower() == user_tone) |
        (recommend_df['style'].str.lower() == user_style) |
        (recommend_df['view'].str.lower() == user_view)
    ]
    return filtered

result_df = filter_recommend_by_user(df_selections, recommend_df, user_index=1)
result_df

,숙소id,color,style,view,시도,숙소url,숙소명,숙소운영형태,예상평점
1,3013510,warm,wood,mountain,강원 고성군,https://place-site.yanolja.com/places/3013510?...,고성왕곡휴펜션,Pension,5.000000
3,3013225,vivid colors,wood,mountain,충북 단양군,https://place-site.yanolja.com/places/3013225?...,단양풀꽃나무펜션,Pension,4.975183
5,3016779,white,modern,mountain,강원 원주시,https://place-site.yanolja.com/places/3016779?...,원주젤코바480풀빌라,Pension,4.967919
9,3013096,white,modern,other,경북 영덕군,https://place-site.yanolja.com/places/3013096?...,영덕하얀집펜션,Pension,4.939931
11,10044478,white,modern,other,인천 강화군,https://place-site.yanolja.com/places/10044478...,강화도플리트비체펜션,Pension,4.911979
...,...,...,...,...,...,...,...,...,...
138,10048356,white,modern,other,강원 춘천시,https://place-site.yanolja.com/places/10048356...,춘천플록스펜션,Pension,4.746722
139,10048707,warm,modern,mountain,경기 남양주시,https://place-site.yanolja.com/places/10048707...,남양주스테이남양주펜션,Pension,4.746446
142,1000088802,white,modern,other,경기 양평군,https://place-site.yanolja.com/places/10000888...,양평인앤인펜션(계곡뷰),Pension,4.746119
146,1000110371,white,modern,other,충남 보령시,https://place-site.yanolja.com/places/10001103...,보령(대천)카카오스토리펜션,Pension,4.744290
148,3014552,vivid colors,modern,other,경남 합천군,https://place-site.yanolja.com/places/3014552?...,합천글램핑스토리,Pension,4.744018

# 숙소 이미지 url 병합

In [2]:
import pandas as pd
df_숙소중복없음 = pd.read_csv('추천숙소정보.csv')
df_이미지 = pd.read_csv('../정제및크롤링/YN_LDGS_PROPRERTY_PHOTO_URL_202412.csv')
df_숙소중복없음

,숙소ID,color,style,view,시도,숙소URL,숙소명,숙소운영형태
0,1000003240,white,minimal,ocean,강원 속초시,https://place-site.yanolja.com/places/10000032...,속초하늘바다펜션,Pension
1,1000052,white,classic,other,강원 강릉시,https://place-site.yanolja.com/places/1000052?...,강릉이화모텔,Motel
2,1000074159,white,minimal,ocean,강원 양양군,https://place-site.yanolja.com/places/10000741...,양양모닝비치펜션(죽도해변),Pension
3,1000080217,dark,minimal,other,대전 유성구,https://place-site.yanolja.com/places/10000802...,대전프리모호텔,Hotel
4,1000080247,white,minimal,other,전남 여수시,https://place-site.yanolja.com/places/10000802...,여수맥스호텔,Hotel
...,...,...,...,...,...,...,...,...
5187,3020716,vivid colors,modern,other,전북 전주시,https://place-site.yanolja.com/places/3020716?...,전주투헤븐호텔,Hotel
5188,3020728,warm,modern,other,전북 전주시,https://place-site.yanolja.com/places/3020728?...,전주바라한호텔,Hotel
5189,3020731,white,modern,other,경기 성남시,https://place-site.yanolja.com/places/3020731?...,성남313에비뉴,Motel
5190,3020733,vivid colors,modern,other,서울 송파구,https://place-site.yanolja.com/places/3020733?...,신천(잠실새내)호텔더캐슬,Motel
5191,3020735,white,minimal,other,인천 강화군,https://place-site.yanolja.com/places/3020735?...,강화도수에뇨펜션,Pension

In [4]:
# LDGS_CD 컬럼명 변경
df_이미지 = df_이미지.rename(columns={'LDGS_CD': '숙소ID'})

In [6]:
# 숙소ID 기준으로 중복제거
df_이미지 = df_이미지.drop_duplicates(subset=['숙소ID'])

In [7]:
df_이미지

,숙소ID,GSRM_CD,LDGS_IMAGE_URL,GSRM_IMAGE_URL,IMAGE_RNEWL_DE
0,23184,2471,NaN,https://yaimg.yanolja.com/resize/place/v4/2017...,2024-11-14 16:02:46.000
19,23192,2484,NaN,https://yaimg.yanolja.com/v5/2022/04/28/10/626...,2024-10-08 16:58:31.000
29,23197,2495,NaN,https://yaimg.yanolja.com/v5/2020/01/20/10/5e2...,2024-04-26 12:15:14.000
34,23204,2504,NaN,https://yaimg.yanolja.com/resize/place/v4/2017...,2023-10-24 17:11:12.000
38,23206,2506,NaN,https://yaimg.yanolja.com/resize/place/v4/2017...,2023-08-15 15:52:11.000
...,...,...,...,...,...
611900,1000113774,379695,NaN,https://yaimg.yanolja.com/v5/2024/08/20/12/66c...,2024-08-20 13:06:15.000
612923,1000113956,482352,NaN,https://yaimg.yanolja.com/v5/2022/08/22/14/630...,2023-04-10 10:27:55.000
613454,1000114058,382948,NaN,https://yaimg.yanolja.com/v5/2021/07/01/12/60d...,2024-01-10 09:56:25.000
614256,1000114237,384687,NaN,https://yaimg.yanolja.com/v5/2021/08/13/10/611...,2023-11-16 12:45:15.000
614895,1000114442,384791,NaN,https://yaimg.yanolja.com/v5/2021/05/26/16/60a...,2024-08-23 16:41:37.000

In [ ]:
# df_숙소중복없음 : 숙소ID, 시도, 숙소명 등 8개 컬럼
# df_이미지       : 숙소ID, GSRM_IMAGE_URL 등 5개 컬럼

# 1) 필요한 컬럼만 추출 (숙소ID, GSRM_IMAGE_URL)
df_img_subset = df_이미지[["숙소ID", "GSRM_IMAGE_URL"]].copy()

# 2) 숙소ID 기준으로 left join
df_urlmerged = pd.merge(
    df_숙소중복없음,
    df_img_subset,
    on="숙소ID",
    how="left"    # 숙소중복없음 기준으로 붙이기
)

# 3) 결과 확인

df_urlmerged

In [10]:
df_urlmerged.to_csv('추천숙소정보0829.csv', index=False)